City: Urbana
Country: United States
Description: University of Illinois at Urbana-Champaign's opportunistic High-Throughput Computing pool
ID: 10270
LongName: University of Illinois at Urbana-Champaign HTC Cluster
Latitude: 40.109647
Longitude: -88.3
State: IL
Zipcode: '61801'
