LongName: Oak Ridge National Lab
Description: Institutional computing center for ORNL
ID: 
AddressLine1: 1 Bethel Valley Road
City: Oak Ridge
Country: USA
Zipcode: "37831"
Latitude: 36
Longitude: -84
