LongName: University of Connecticut
Description: The University of Connecticut UConn-cedar cluster 

ID: 10269
AddressLine1: 2152 Hillside Road
City: Storrs

Country: US
State: CT
Zipcode: "06269-3046"

Latitude: 41.8084
Longitude: -72.2495
